se: Fix Wbool-conversion warning in find_specific_rule()
find_specific_rule() returns pointer, so obviously 'return false' is
just confusingly stupid.  Newer clang (e.g. on ArchLinux) also
complains:

  se/ace.c:661:10: error: initialization of pointer of type 'struct seel_ace_rule *' to null from a constant boolean expression [-Werror,-Wbool-conversion]

Fixes: 1be05e63e0a1 ("se: Initial commit")
Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>