include: include endian.h to fix missing __BYTE_ORDER definition on Debian Stretch
Code should pull explicitly headers for necessary symbols instead of
relying on dependencies.  Lack of endian.h caused build failures on
Debian Stretch:

    In file included from tools/nfctool/ndef-decode.c:28:0:
    include/near/types.h:43:5: error: "__BYTE_ORDER" is not defined [-Werror=undef]
     #if __BYTE_ORDER == __LITTLE_ENDIAN

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>